-- ========================================
-- OA HR Management System Schema
-- ========================================

-- 1. 部门表
CREATE TABLE OA_DEPARTMENT (
    DEPT_ID NUMBER PRIMARY KEY,
    DEPT_NAME VARCHAR2(100) NOT NULL,
    PARENT_ID NUMBER,
    DEPT_LEVEL NUMBER DEFAULT 1,
    MANAGER_ID NUMBER,
    DESCRIPTION VARCHAR2(500),
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
    SORT_ORDER NUMBER DEFAULT 0,
    CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_DEPT_PARENT FOREIGN KEY (PARENT_ID) REFERENCES OA_DEPARTMENT(DEPT_ID)
);

CREATE SEQUENCE SEQ_OA_DEPARTMENT START WITH 1 INCREMENT BY 1;

COMMENT ON TABLE OA_DEPARTMENT IS '部门信息表';
COMMENT ON COLUMN OA_DEPARTMENT.PARENT_ID IS '父部门ID，NULL表示顶级部门';
COMMENT ON COLUMN OA_DEPARTMENT.DEPT_LEVEL IS '部门层级，1为顶级';
COMMENT ON COLUMN OA_DEPARTMENT.STATUS IS 'ACTIVE-启用, INACTIVE-停用';

CREATE INDEX IDX_DEPT_PARENT ON OA_DEPARTMENT(PARENT_ID);
CREATE INDEX IDX_DEPT_MANAGER ON OA_DEPARTMENT(MANAGER_ID);

-- 2. 岗位表
CREATE TABLE OA_POSITION (
    POSITION_ID NUMBER PRIMARY KEY,
    POSITION_NAME VARCHAR2(100) NOT NULL,
    DEPT_ID NUMBER,
    POSITION_LEVEL VARCHAR2(50),
    DESCRIPTION VARCHAR2(500),
    RESPONSIBILITIES CLOB,
    REQUIREMENTS CLOB,
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
    CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_POSITION_DEPT FOREIGN KEY (DEPT_ID) REFERENCES OA_DEPARTMENT(DEPT_ID)
);

CREATE SEQUENCE SEQ_OA_POSITION START WITH 1 INCREMENT BY 1;

COMMENT ON TABLE OA_POSITION IS '岗位信息表';
COMMENT ON COLUMN OA_POSITION.POSITION_LEVEL IS '岗位级别：JUNIOR-初级, MIDDLE-中级, SENIOR-高级, EXPERT-专家';
COMMENT ON COLUMN OA_POSITION.STATUS IS 'ACTIVE-启用, INACTIVE-停用';

CREATE INDEX IDX_POSITION_DEPT ON OA_POSITION(DEPT_ID);

-- 3. 员工档案扩展表
CREATE TABLE OA_EMPLOYEE_PROFILE (
    PROFILE_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL UNIQUE,
    DEPT_ID NUMBER,
    POSITION_ID NUMBER,
    ID_CARD VARCHAR2(18),
    GENDER VARCHAR2(10),
    BIRTH_DATE DATE,
    EDUCATION VARCHAR2(50),
    MAJOR VARCHAR2(100),
    SCHOOL VARCHAR2(200),
    JOIN_DATE DATE,
    REGULAR_DATE DATE,
    WORK_STATUS VARCHAR2(20) DEFAULT 'PROBATION',
    EMERGENCY_CONTACT VARCHAR2(100),
    EMERGENCY_PHONE VARCHAR2(20),
    ADDRESS VARCHAR2(500),
    BANK_NAME VARCHAR2(100),
    BANK_ACCOUNT VARCHAR2(50),
    CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_PROFILE_DEPT FOREIGN KEY (DEPT_ID) REFERENCES OA_DEPARTMENT(DEPT_ID),
    CONSTRAINT FK_PROFILE_POSITION FOREIGN KEY (POSITION_ID) REFERENCES OA_POSITION(POSITION_ID)
);

CREATE SEQUENCE SEQ_OA_EMPLOYEE_PROFILE START WITH 1 INCREMENT BY 1;

COMMENT ON TABLE OA_EMPLOYEE_PROFILE IS '员工档案扩展表';
COMMENT ON COLUMN OA_EMPLOYEE_PROFILE.EDUCATION IS '学历：HIGH_SCHOOL-高中, COLLEGE-大专, BACHELOR-本科, MASTER-硕士, DOCTOR-博士';
COMMENT ON COLUMN OA_EMPLOYEE_PROFILE.WORK_STATUS IS 'PROBATION-试用期, REGULAR-正式, RESIGNED-离职';

CREATE INDEX IDX_PROFILE_USER ON OA_EMPLOYEE_PROFILE(USER_ID);
CREATE INDEX IDX_PROFILE_DEPT ON OA_EMPLOYEE_PROFILE(DEPT_ID);

-- 4. 员工合同表
CREATE TABLE OA_EMPLOYEE_CONTRACT (
    CONTRACT_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    CONTRACT_NO VARCHAR2(50) UNIQUE,
    CONTRACT_TYPE VARCHAR2(50),
    START_DATE DATE NOT NULL,
    END_DATE DATE,
    DURATION_YEARS NUMBER(3,1),
    SALARY_LEVEL VARCHAR2(50),
    PROBATION_MONTHS NUMBER DEFAULT 3,
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
    FILE_PATH VARCHAR2(500),
    REMARK VARCHAR2(500),
    CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE SEQUENCE SEQ_OA_EMPLOYEE_CONTRACT START WITH 1 INCREMENT BY 1;

COMMENT ON TABLE OA_EMPLOYEE_CONTRACT IS '员工合同表';
COMMENT ON COLUMN OA_EMPLOYEE_CONTRACT.CONTRACT_TYPE IS 'LABOR-劳动合同, INTERNSHIP-实习合同, PART_TIME-兼职合同';
COMMENT ON COLUMN OA_EMPLOYEE_CONTRACT.STATUS IS 'ACTIVE-有效, EXPIRED-已过期, TERMINATED-已终止';

CREATE INDEX IDX_CONTRACT_USER ON OA_EMPLOYEE_CONTRACT(USER_ID);

-- ========================================
-- 初始化数据
-- ========================================

-- 插入顶级部门
INSERT INTO OA_DEPARTMENT (DEPT_ID, DEPT_NAME, PARENT_ID, DEPT_LEVEL, DESCRIPTION, STATUS, SORT_ORDER)
VALUES (SEQ_OA_DEPARTMENT.NEXTVAL, '总经办', NULL, 1, '公司最高管理层', 'ACTIVE', 1);

INSERT INTO OA_DEPARTMENT (DEPT_ID, DEPT_NAME, PARENT_ID, DEPT_LEVEL, DESCRIPTION, STATUS, SORT_ORDER)
VALUES (SEQ_OA_DEPARTMENT.NEXTVAL, '技术部', NULL, 1, '负责技术研发和产品开发', 'ACTIVE', 2);

INSERT INTO OA_DEPARTMENT (DEPT_ID, DEPT_NAME, PARENT_ID, DEPT_LEVEL, DESCRIPTION, STATUS, SORT_ORDER)
VALUES (SEQ_OA_DEPARTMENT.NEXTVAL, '市场部', NULL, 1, '负责市场营销和品牌推广', 'ACTIVE', 3);

INSERT INTO OA_DEPARTMENT (DEPT_ID, DEPT_NAME, PARENT_ID, DEPT_LEVEL, DESCRIPTION, STATUS, SORT_ORDER)
VALUES (SEQ_OA_DEPARTMENT.NEXTVAL, '人力资源部', NULL, 1, '负责人力资源管理', 'ACTIVE', 4);

-- 插入二级部门（技术部下属）
INSERT INTO OA_DEPARTMENT (DEPT_ID, DEPT_NAME, PARENT_ID, DEPT_LEVEL, DESCRIPTION, STATUS, SORT_ORDER)
VALUES (SEQ_OA_DEPARTMENT.NEXTVAL, '前端开发组', 2, 2, '负责前端产品开发', 'ACTIVE', 1);

INSERT INTO OA_DEPARTMENT (DEPT_ID, DEPT_NAME, PARENT_ID, DEPT_LEVEL, DESCRIPTION, STATUS, SORT_ORDER)
VALUES (SEQ_OA_DEPARTMENT.NEXTVAL, '后端开发组', 2, 2, '负责后端服务开发', 'ACTIVE', 2);

INSERT INTO OA_DEPARTMENT (DEPT_ID, DEPT_NAME, PARENT_ID, DEPT_LEVEL, DESCRIPTION, STATUS, SORT_ORDER)
VALUES (SEQ_OA_DEPARTMENT.NEXTVAL, '测试组', 2, 2, '负责产品质量保证', 'ACTIVE', 3);

-- 插入岗位信息
INSERT INTO OA_POSITION (POSITION_ID, POSITION_NAME, DEPT_ID, POSITION_LEVEL, DESCRIPTION, STATUS)
VALUES (SEQ_OA_POSITION.NEXTVAL, '总经理', 1, 'EXPERT', '公司最高管理者', 'ACTIVE');

INSERT INTO OA_POSITION (POSITION_ID, POSITION_NAME, DEPT_ID, POSITION_LEVEL, DESCRIPTION, STATUS)
VALUES (SEQ_OA_POSITION.NEXTVAL, '技术总监', 2, 'SENIOR', '技术部门负责人', 'ACTIVE');

INSERT INTO OA_POSITION (POSITION_ID, POSITION_NAME, DEPT_ID, POSITION_LEVEL, DESCRIPTION, STATUS)
VALUES (SEQ_OA_POSITION.NEXTVAL, '前端工程师', 5, 'MIDDLE', '负责前端开发工作', 'ACTIVE');

INSERT INTO OA_POSITION (POSITION_ID, POSITION_NAME, DEPT_ID, POSITION_LEVEL, DESCRIPTION, STATUS)
VALUES (SEQ_OA_POSITION.NEXTVAL, '后端工程师', 6, 'MIDDLE', '负责后端开发工作', 'ACTIVE');

INSERT INTO OA_POSITION (POSITION_ID, POSITION_NAME, DEPT_ID, POSITION_LEVEL, DESCRIPTION, STATUS)
VALUES (SEQ_OA_POSITION.NEXTVAL, '测试工程师', 7, 'JUNIOR', '负责软件测试工作', 'ACTIVE');

INSERT INTO OA_POSITION (POSITION_ID, POSITION_NAME, DEPT_ID, POSITION_LEVEL, DESCRIPTION, STATUS)
VALUES (SEQ_OA_POSITION.NEXTVAL, 'HR专员', 4, 'MIDDLE', '负责人力资源日常工作', 'ACTIVE');

-- 插入员工档案示例（假设USER_ID=1存在）
INSERT INTO OA_EMPLOYEE_PROFILE (PROFILE_ID, USER_ID, DEPT_ID, POSITION_ID, ID_CARD, GENDER, BIRTH_DATE, EDUCATION, MAJOR, SCHOOL, JOIN_DATE, WORK_STATUS)
VALUES (SEQ_OA_EMPLOYEE_PROFILE.NEXTVAL, 1, 2, 2, '110101199001011234', 'MALE', 
        TO_DATE('1990-01-01', 'YYYY-MM-DD'), 'BACHELOR', '计算机科学与技术', '北京大学',
        TO_DATE('2020-01-01', 'YYYY-MM-DD'), 'REGULAR');

-- 插入合同示例
INSERT INTO OA_EMPLOYEE_CONTRACT (CONTRACT_ID, USER_ID, CONTRACT_NO, CONTRACT_TYPE, START_DATE, END_DATE, DURATION_YEARS, PROBATION_MONTHS, STATUS)
VALUES (SEQ_OA_EMPLOYEE_CONTRACT.NEXTVAL, 1, 'CON-2020-001', 'LABOR', 
        TO_DATE('2020-01-01', 'YYYY-MM-DD'), 
        TO_DATE('2023-01-01', 'YYYY-MM-DD'), 
        3, 3, 'ACTIVE');

COMMIT;
