-- ========================================
-- OA System Database Schema (MySQL)
-- ========================================

-- 1. Car Management Table
CREATE TABLE IF NOT EXISTS OA_CAR (
    CAR_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    LICENSE_PLATE VARCHAR(20) NOT NULL UNIQUE,
    BRAND VARCHAR(50),
    MODEL VARCHAR(50),
    SEATS INT,
    STATUS VARCHAR(20) DEFAULT 'AVAILABLE',
    MILEAGE INT,
    LAST_MAINTENANCE_DATE DATE,
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Comments are not supported in the same way as Oracle's COMMENT ON, 
-- but we can add them inline if needed, or skip for now as they are metadata.

-- Insert sample data
INSERT INTO OA_CAR (LICENSE_PLATE, BRAND, MODEL, SEATS, STATUS, MILEAGE) 
VALUES ('京A12345', 'Toyota', 'Camry', 5, 'AVAILABLE', 50000);

INSERT INTO OA_CAR (LICENSE_PLATE, BRAND, MODEL, SEATS, STATUS, MILEAGE) 
VALUES ('京B67890', 'Honda', 'Accord', 5, 'IN_USE', 30000);

INSERT INTO OA_CAR (LICENSE_PLATE, BRAND, MODEL, SEATS, STATUS, MILEAGE) 
VALUES ('京C11111', 'Volkswagen', 'Passat', 5, 'MAINTENANCE', 80000);

-- 4. Car Application (For Schedule Integration)
CREATE TABLE IF NOT EXISTS OA_CAR_APPLICATION (
    APPLICATION_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CAR_ID BIGINT,
    USER_ID BIGINT,
    TITLE VARCHAR(200),
    DESTINATION VARCHAR(200),
    START_TIME DATETIME,
    END_TIME DATETIME,
    PASSENGERS INT,
    REASON TEXT,
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CAR_APP_CAR FOREIGN KEY (CAR_ID) REFERENCES OA_CAR(CAR_ID)
);

-- Insert sample car application
INSERT INTO OA_CAR_APPLICATION (CAR_ID, USER_ID, TITLE, DESTINATION, START_TIME, END_TIME, PASSENGERS, REASON, STATUS)
VALUES (1, 1, '用车申请_市区调研', '海淀区中关村', 
        '2026-01-10 08:00:00', 
        '2026-01-10 18:00:00', 
        3, '前往中关村进行市场调研', 'APPROVED');

COMMIT;
