-- ========================================
-- OA Finance Management System Schema
-- ========================================

-- 1. 费用类型表
CREATE TABLE OA_EXPENSE_TYPE (
    TYPE_ID NUMBER PRIMARY KEY,
    TYPE_NAME VARCHAR2(100) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR2(500),
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
    CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE SEQUENCE SEQ_OA_EXPENSE_TYPE START WITH 1 INCREMENT BY 1;

COMMENT ON TABLE OA_EXPENSE_TYPE IS '费用类型表';
COMMENT ON COLUMN OA_EXPENSE_TYPE.STATUS IS 'ACTIVE-启用, INACTIVE-停用';

-- 2. 报销申请表
CREATE TABLE OA_EXPENSE_CLAIM (
    CLAIM_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    CLAIM_NO VARCHAR2(50) UNIQUE NOT NULL,
    EXPENSE_TYPE_ID NUMBER,
    TOTAL_AMOUNT NUMBER(10,2) NOT NULL,
    CLAIM_DATE DATE DEFAULT SYSDATE,
    DESCRIPTION CLOB,
    STATUS VARCHAR2(20) DEFAULT 'PENDING',
    APPROVER_ID NUMBER,
    APPROVE_TIME TIMESTAMP,
    APPROVE_REMARK VARCHAR2(500),
    PAYMENT_STATUS VARCHAR2(20) DEFAULT 'UNPAID',
    PAYMENT_DATE DATE,
    CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_CLAIM_TYPE FOREIGN KEY (EXPENSE_TYPE_ID) REFERENCES OA_EXPENSE_TYPE(TYPE_ID)
);

CREATE SEQUENCE SEQ_OA_EXPENSE_CLAIM START WITH 1 INCREMENT BY 1;

COMMENT ON TABLE OA_EXPENSE_CLAIM IS '报销申请表';
COMMENT ON COLUMN OA_EXPENSE_CLAIM.CLAIM_NO IS '报销单号，格式：EXP-YYYYMMDD-序号';
COMMENT ON COLUMN OA_EXPENSE_CLAIM.STATUS IS 'PENDING-待审批, APPROVED-已批准, REJECTED-已拒绝, CANCELLED-已取消';
COMMENT ON COLUMN OA_EXPENSE_CLAIM.PAYMENT_STATUS IS 'UNPAID-未支付, PAID-已支付, PROCESSING-支付中';

CREATE INDEX IDX_CLAIM_USER ON OA_EXPENSE_CLAIM(USER_ID);
CREATE INDEX IDX_CLAIM_STATUS ON OA_EXPENSE_CLAIM(STATUS);
CREATE INDEX IDX_CLAIM_DATE ON OA_EXPENSE_CLAIM(CLAIM_DATE);

-- 3. 发票信息表
CREATE TABLE OA_INVOICE (
    INVOICE_ID NUMBER PRIMARY KEY,
    CLAIM_ID NUMBER NOT NULL,
    INVOICE_NO VARCHAR2(50),
    INVOICE_TYPE VARCHAR2(50),
    AMOUNT NUMBER(10,2) NOT NULL,
    INVOICE_DATE DATE,
    COMPANY_NAME VARCHAR2(200),
    TAX_NO VARCHAR2(50),
    FILE_PATH VARCHAR2(500),
    REMARK VARCHAR2(500),
    CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_INVOICE_CLAIM FOREIGN KEY (CLAIM_ID) REFERENCES OA_EXPENSE_CLAIM(CLAIM_ID)
);

CREATE SEQUENCE SEQ_OA_INVOICE START WITH 1 INCREMENT BY 1;

COMMENT ON TABLE OA_INVOICE IS '发票信息表';
COMMENT ON COLUMN OA_INVOICE.INVOICE_TYPE IS 'VAT_SPECIAL-增值税专用发票, VAT_ORDINARY-增值税普通发票, RECEIPT-收据, OTHER-其他';

CREATE INDEX IDX_INVOICE_CLAIM ON OA_INVOICE(CLAIM_ID);

-- ========================================
-- 初始化数据
-- ========================================

-- 插入费用类型
INSERT INTO OA_EXPENSE_TYPE (TYPE_ID, TYPE_NAME, DESCRIPTION, STATUS)
VALUES (SEQ_OA_EXPENSE_TYPE.NEXTVAL, '差旅费', '出差产生的交通、住宿、餐饮等费用', 'ACTIVE');

INSERT INTO OA_EXPENSE_TYPE (TYPE_ID, TYPE_NAME, DESCRIPTION, STATUS)
VALUES (SEQ_OA_EXPENSE_TYPE.NEXTVAL, '办公用品', '办公文具、设备等采购费用', 'ACTIVE');

INSERT INTO OA_EXPENSE_TYPE (TYPE_ID, TYPE_NAME, DESCRIPTION, STATUS)
VALUES (SEQ_OA_EXPENSE_TYPE.NEXTVAL, '通讯费', '电话费、网络费等通讯费用', 'ACTIVE');

INSERT INTO OA_EXPENSE_TYPE (TYPE_ID, TYPE_NAME, DESCRIPTION, STATUS)
VALUES (SEQ_OA_EXPENSE_TYPE.NEXTVAL, '招待费', '客户接待、商务宴请等费用', 'ACTIVE');

INSERT INTO OA_EXPENSE_TYPE (TYPE_ID, TYPE_NAME, DESCRIPTION, STATUS)
VALUES (SEQ_OA_EXPENSE_TYPE.NEXTVAL, '培训费', '员工培训、学习等费用', 'ACTIVE');

INSERT INTO OA_EXPENSE_TYPE (TYPE_ID, TYPE_NAME, DESCRIPTION, STATUS)
VALUES (SEQ_OA_EXPENSE_TYPE.NEXTVAL, '其他费用', '其他日常费用', 'ACTIVE');

-- 插入测试报销申请（假设USER_ID=1存在）
INSERT INTO OA_EXPENSE_CLAIM (CLAIM_ID, USER_ID, CLAIM_NO, EXPENSE_TYPE_ID, TOTAL_AMOUNT, CLAIM_DATE, DESCRIPTION, STATUS)
VALUES (SEQ_OA_EXPENSE_CLAIM.NEXTVAL, 1, 'EXP-20260106-001', 1, 2580.00, 
        TO_DATE('2026-01-06', 'YYYY-MM-DD'), 
        '北京-上海出差，包含高铁票、酒店住宿及餐饮费用', 'PENDING');

INSERT INTO OA_EXPENSE_CLAIM (CLAIM_ID, USER_ID, CLAIM_NO, EXPENSE_TYPE_ID, TOTAL_AMOUNT, CLAIM_DATE, DESCRIPTION, STATUS, APPROVER_ID, APPROVE_TIME, PAYMENT_STATUS)
VALUES (SEQ_OA_EXPENSE_CLAIM.NEXTVAL, 1, 'EXP-20260105-001', 2, 350.00, 
        TO_DATE('2026-01-05', 'YYYY-MM-DD'), 
        '采购办公用品：打印纸、文件夹等', 'APPROVED', 2, SYSTIMESTAMP, 'PAID');

-- 插入测试发票信息
INSERT INTO OA_INVOICE (INVOICE_ID, CLAIM_ID, INVOICE_NO, INVOICE_TYPE, AMOUNT, INVOICE_DATE, COMPANY_NAME)
VALUES (SEQ_OA_INVOICE.NEXTVAL, 1, '12345678901234567890', 'VAT_ORDINARY', 1200.00, 
        TO_DATE('2026-01-05', 'YYYY-MM-DD'), '中国铁路客票');

INSERT INTO OA_INVOICE (INVOICE_ID, CLAIM_ID, INVOICE_NO, INVOICE_TYPE, AMOUNT, INVOICE_DATE, COMPANY_NAME)
VALUES (SEQ_OA_INVOICE.NEXTVAL, 1, '98765432109876543210', 'VAT_ORDINARY', 1380.00, 
        TO_DATE('2026-01-05', 'YYYY-MM-DD'), '如家酒店');

COMMIT;
