-- ========================================
-- OA System Database Schema (Oracle)
-- ========================================

-- 1. Car Management Table
CREATE TABLE OA_CAR (
    CAR_ID NUMBER PRIMARY KEY,
    LICENSE_PLATE VARCHAR2(20) NOT NULL UNIQUE,
    BRAND VARCHAR2(50),
    MODEL VARCHAR2(50),
    SEATS NUMBER,
    STATUS VARCHAR2(20) DEFAULT 'AVAILABLE',
    MILEAGE NUMBER,
    LAST_MAINTENANCE_DATE DATE,
    CREATE_TIME DATE DEFAULT SYSDATE,
    UPDATE_TIME DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SEQ_OA_CAR START WITH 1 INCREMENT BY 1;

COMMENT ON TABLE OA_CAR IS 'Vehicle Management Table';
COMMENT ON COLUMN OA_CAR.STATUS IS 'AVAILABLE, IN_USE, MAINTENANCE';

-- Insert sample data
INSERT INTO OA_CAR (CAR_ID, LICENSE_PLATE, BRAND, MODEL, SEATS, STATUS, MILEAGE) 
VALUES (SEQ_OA_CAR.NEXTVAL, '京A12345', 'Toyota', 'Camry', 5, 'AVAILABLE', 50000);

INSERT INTO OA_CAR (CAR_ID, LICENSE_PLATE, BRAND, MODEL, SEATS, STATUS, MILEAGE) 
VALUES (SEQ_OA_CAR.NEXTVAL, '京B67890', 'Honda', 'Accord', 5, 'IN_USE', 30000);

INSERT INTO OA_CAR (CAR_ID, LICENSE_PLATE, BRAND, MODEL, SEATS, STATUS, MILEAGE) 
VALUES (SEQ_OA_CAR.NEXTVAL, '京C11111', 'Volkswagen', 'Passat', 5, 'MAINTENANCE', 80000);

COMMIT;

-- ========================================
-- Note: The following tables are assumed to exist
-- from previous development phases
-- ========================================

-- 2. Meeting Room Booking (Reference)
-- CREATE TABLE OA_MEETING_BOOKING (
--     BOOKING_ID NUMBER PRIMARY KEY,
--     ROOM_ID NUMBER,
--     USER_ID NUMBER,
--     TITLE VARCHAR2(200),
--     START_TIME DATE,
--     END_TIME DATE,
--     STATUS VARCHAR2(20),
--     CREATE_TIME DATE DEFAULT SYSDATE
-- );

-- 3. Workflow Tasks (Reference)
-- CREATE TABLE OA_WORKFLOW (
--     WORKFLOW_ID NUMBER PRIMARY KEY,
--     TITLE VARCHAR2(200),
--     INITIATOR_ID NUMBER,
--     TYPE VARCHAR2(50),
--     STATUS VARCHAR2(20),
--     DUE_DATE DATE,
--     CREATE_TIME DATE DEFAULT SYSDATE
-- );

-- 4. Car Application (For Schedule Integration)
CREATE TABLE OA_CAR_APPLICATION (
    APPLICATION_ID NUMBER PRIMARY KEY,
    CAR_ID NUMBER,
    USER_ID NUMBER,
    TITLE VARCHAR2(200),
    DESTINATION VARCHAR2(200),
    START_TIME DATE,
    END_TIME DATE,
    PASSENGERS NUMBER,
    REASON CLOB,
    STATUS VARCHAR2(20) DEFAULT 'PENDING',
    CREATE_TIME DATE DEFAULT SYSDATE,
    CONSTRAINT FK_CAR_APP_CAR FOREIGN KEY (CAR_ID) REFERENCES OA_CAR(CAR_ID)
);

CREATE SEQUENCE SEQ_OA_CAR_APP START WITH 1 INCREMENT BY 1;

COMMENT ON TABLE OA_CAR_APPLICATION IS 'Car Usage Application Records';

-- Insert sample car application
INSERT INTO OA_CAR_APPLICATION (APPLICATION_ID, CAR_ID, USER_ID, TITLE, DESTINATION, START_TIME, END_TIME, PASSENGERS, REASON, STATUS)
VALUES (SEQ_OA_CAR_APP.NEXTVAL, 1, 1, '用车申请_市区调研', '海淀区中关村', 
        TO_DATE('2026-01-10 08:00', 'YYYY-MM-DD HH24:MI'), 
        TO_DATE('2026-01-10 18:00', 'YYYY-MM-DD HH24:MI'), 
        3, '前往中关村进行市场调研', 'APPROVED');

COMMIT;
