-- ========================================
-- OA Attendance Management System Schema
-- ========================================

-- 1. 考勤打卡记录表
CREATE TABLE OA_ATTENDANCE (
    ATTENDANCE_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    WORK_DATE DATE NOT NULL,
    CLOCK_IN_TIME TIMESTAMP,
    CLOCK_OUT_TIME TIMESTAMP,
    CLOCK_IN_LOCATION VARCHAR2(200),
    CLOCK_OUT_LOCATION VARCHAR2(200),
    STATUS VARCHAR2(20) DEFAULT 'NORMAL',
    WORK_HOURS NUMBER(5,2),
    IS_LATE NUMBER(1) DEFAULT 0,
    IS_EARLY_LEAVE NUMBER(1) DEFAULT 0,
    REMARK VARCHAR2(500),
    CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE SEQUENCE SEQ_OA_ATTENDANCE START WITH 1 INCREMENT BY 1;

COMMENT ON TABLE OA_ATTENDANCE IS '考勤打卡记录表';
COMMENT ON COLUMN OA_ATTENDANCE.STATUS IS 'NORMAL-正常, LATE-迟到, EARLY_LEAVE-早退, ABSENT-缺勤';
COMMENT ON COLUMN OA_ATTENDANCE.IS_LATE IS '0-未迟到, 1-迟到';
COMMENT ON COLUMN OA_ATTENDANCE.IS_EARLY_LEAVE IS '0-未早退, 1-早退';

CREATE INDEX IDX_ATTENDANCE_USER_DATE ON OA_ATTENDANCE(USER_ID, WORK_DATE);

-- 2. 请假申请表
CREATE TABLE OA_LEAVE_REQUEST (
    REQUEST_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    LEAVE_TYPE VARCHAR2(50) NOT NULL,
    START_TIME TIMESTAMP NOT NULL,
    END_TIME TIMESTAMP NOT NULL,
    DAYS NUMBER(5,1) NOT NULL,
    REASON CLOB,
    STATUS VARCHAR2(20) DEFAULT 'PENDING',
    APPROVER_ID NUMBER,
    APPROVE_TIME TIMESTAMP,
    APPROVE_REMARK VARCHAR2(500),
    CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE SEQUENCE SEQ_OA_LEAVE_REQUEST START WITH 1 INCREMENT BY 1;

COMMENT ON TABLE OA_LEAVE_REQUEST IS '请假申请表';
COMMENT ON COLUMN OA_LEAVE_REQUEST.LEAVE_TYPE IS 'SICK-病假, ANNUAL-年假, PERSONAL-事假, MARRIAGE-婚假, MATERNITY-产假, PATERNITY-陪产假, BEREAVEMENT-丧假';
COMMENT ON COLUMN OA_LEAVE_REQUEST.STATUS IS 'PENDING-待审批, APPROVED-已批准, REJECTED-已拒绝, CANCELLED-已取消';

CREATE INDEX IDX_LEAVE_USER ON OA_LEAVE_REQUEST(USER_ID);
CREATE INDEX IDX_LEAVE_STATUS ON OA_LEAVE_REQUEST(STATUS);

-- 3. 加班申请表
CREATE TABLE OA_OVERTIME_REQUEST (
    REQUEST_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    OVERTIME_DATE DATE NOT NULL,
    START_TIME TIMESTAMP NOT NULL,
    END_TIME TIMESTAMP NOT NULL,
    HOURS NUMBER(5,2) NOT NULL,
    REASON CLOB,
    STATUS VARCHAR2(20) DEFAULT 'PENDING',
    APPROVER_ID NUMBER,
    APPROVE_TIME TIMESTAMP,
    APPROVE_REMARK VARCHAR2(500),
    CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE SEQUENCE SEQ_OA_OVERTIME_REQUEST START WITH 1 INCREMENT BY 1;

COMMENT ON TABLE OA_OVERTIME_REQUEST IS '加班申请表';
COMMENT ON COLUMN OA_OVERTIME_REQUEST.STATUS IS 'PENDING-待审批, APPROVED-已批准, REJECTED-已拒绝, CANCELLED-已取消';

CREATE INDEX IDX_OVERTIME_USER ON OA_OVERTIME_REQUEST(USER_ID);
CREATE INDEX IDX_OVERTIME_DATE ON OA_OVERTIME_REQUEST(OVERTIME_DATE);

-- 4. 出差申请表
CREATE TABLE OA_BUSINESS_TRIP (
    TRIP_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    DESTINATION VARCHAR2(200) NOT NULL,
    START_TIME TIMESTAMP NOT NULL,
    END_TIME TIMESTAMP NOT NULL,
    DAYS NUMBER(5,1) NOT NULL,
    PURPOSE CLOB,
    TRANSPORT_TYPE VARCHAR2(50),
    ESTIMATED_COST NUMBER(10,2),
    STATUS VARCHAR2(20) DEFAULT 'PENDING',
    APPROVER_ID NUMBER,
    APPROVE_TIME TIMESTAMP,
    APPROVE_REMARK VARCHAR2(500),
    CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE SEQUENCE SEQ_OA_BUSINESS_TRIP START WITH 1 INCREMENT BY 1;

COMMENT ON TABLE OA_BUSINESS_TRIP IS '出差申请表';
COMMENT ON COLUMN OA_BUSINESS_TRIP.TRANSPORT_TYPE IS 'FLIGHT-飞机, TRAIN-火车, CAR-汽车, OTHER-其他';
COMMENT ON COLUMN OA_BUSINESS_TRIP.STATUS IS 'PENDING-待审批, APPROVED-已批准, REJECTED-已拒绝, CANCELLED-已取消';

CREATE INDEX IDX_TRIP_USER ON OA_BUSINESS_TRIP(USER_ID);
CREATE INDEX IDX_TRIP_STATUS ON OA_BUSINESS_TRIP(STATUS);

-- 5. 考勤规则配置表
CREATE TABLE OA_ATTENDANCE_RULE (
    RULE_ID NUMBER PRIMARY KEY,
    RULE_NAME VARCHAR2(100) NOT NULL,
    WORK_START_TIME VARCHAR2(10) DEFAULT '09:00',
    WORK_END_TIME VARCHAR2(10) DEFAULT '18:00',
    LATE_THRESHOLD_MINUTES NUMBER DEFAULT 15,
    EARLY_LEAVE_THRESHOLD_MINUTES NUMBER DEFAULT 15,
    WORK_DAYS_PER_WEEK NUMBER DEFAULT 5,
    IS_FLEXIBLE NUMBER(1) DEFAULT 0,
    IS_DEFAULT NUMBER(1) DEFAULT 0,
    CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE SEQUENCE SEQ_OA_ATTENDANCE_RULE START WITH 1 INCREMENT BY 1;

COMMENT ON TABLE OA_ATTENDANCE_RULE IS '考勤规则配置表';
COMMENT ON COLUMN OA_ATTENDANCE_RULE.IS_FLEXIBLE IS '0-固定工时, 1-弹性工时';
COMMENT ON COLUMN OA_ATTENDANCE_RULE.IS_DEFAULT IS '0-非默认, 1-默认规则';

-- 6. 月度考勤汇总表
CREATE TABLE OA_ATTENDANCE_SUMMARY (
    SUMMARY_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    YEAR_MONTH VARCHAR2(7) NOT NULL,
    WORK_DAYS NUMBER DEFAULT 0,
    ACTUAL_DAYS NUMBER DEFAULT 0,
    LATE_TIMES NUMBER DEFAULT 0,
    EARLY_LEAVE_TIMES NUMBER DEFAULT 0,
    ABSENT_DAYS NUMBER DEFAULT 0,
    LEAVE_DAYS NUMBER(5,1) DEFAULT 0,
    OVERTIME_HOURS NUMBER(6,2) DEFAULT 0,
    TRIP_DAYS NUMBER(5,1) DEFAULT 0,
    ATTENDANCE_RATE NUMBER(5,2),
    CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT UK_SUMMARY_USER_MONTH UNIQUE (USER_ID, YEAR_MONTH)
);

CREATE SEQUENCE SEQ_OA_ATTENDANCE_SUMMARY START WITH 1 INCREMENT BY 1;

COMMENT ON TABLE OA_ATTENDANCE_SUMMARY IS '月度考勤汇总表';
COMMENT ON COLUMN OA_ATTENDANCE_SUMMARY.YEAR_MONTH IS '年月格式: 2026-01';
COMMENT ON COLUMN OA_ATTENDANCE_SUMMARY.WORK_DAYS IS '应出勤天数';
COMMENT ON COLUMN OA_ATTENDANCE_SUMMARY.ACTUAL_DAYS IS '实际出勤天数';
COMMENT ON COLUMN OA_ATTENDANCE_SUMMARY.ATTENDANCE_RATE IS '出勤率(百分比)';

CREATE INDEX IDX_SUMMARY_USER_MONTH ON OA_ATTENDANCE_SUMMARY(USER_ID, YEAR_MONTH);

-- ========================================
-- 初始化数据
-- ========================================

-- 插入默认考勤规则
INSERT INTO OA_ATTENDANCE_RULE (RULE_ID, RULE_NAME, WORK_START_TIME, WORK_END_TIME, LATE_THRESHOLD_MINUTES, EARLY_LEAVE_THRESHOLD_MINUTES, WORK_DAYS_PER_WEEK, IS_FLEXIBLE, IS_DEFAULT)
VALUES (SEQ_OA_ATTENDANCE_RULE.NEXTVAL, '标准工作制', '09:00', '18:00', 15, 15, 5, 0, 1);

INSERT INTO OA_ATTENDANCE_RULE (RULE_ID, RULE_NAME, WORK_START_TIME, WORK_END_TIME, LATE_THRESHOLD_MINUTES, EARLY_LEAVE_THRESHOLD_MINUTES, WORK_DAYS_PER_WEEK, IS_FLEXIBLE, IS_DEFAULT)
VALUES (SEQ_OA_ATTENDANCE_RULE.NEXTVAL, '弹性工作制', '09:00', '18:00', 30, 30, 5, 1, 0);

-- 插入测试考勤数据 (假设USER_ID=1存在)
INSERT INTO OA_ATTENDANCE (ATTENDANCE_ID, USER_ID, WORK_DATE, CLOCK_IN_TIME, CLOCK_OUT_TIME, CLOCK_IN_LOCATION, CLOCK_OUT_LOCATION, STATUS, WORK_HOURS, IS_LATE, IS_EARLY_LEAVE)
VALUES (SEQ_OA_ATTENDANCE.NEXTVAL, 1, TO_DATE('2026-01-06', 'YYYY-MM-DD'), 
        TO_TIMESTAMP('2026-01-06 08:55:00', 'YYYY-MM-DD HH24:MI:SS'),
        TO_TIMESTAMP('2026-01-06 18:10:00', 'YYYY-MM-DD HH24:MI:SS'),
        '北京市海淀区', '北京市海淀区', 'NORMAL', 9.25, 0, 0);

INSERT INTO OA_ATTENDANCE (ATTENDANCE_ID, USER_ID, WORK_DATE, CLOCK_IN_TIME, CLOCK_OUT_TIME, CLOCK_IN_LOCATION, CLOCK_OUT_LOCATION, STATUS, WORK_HOURS, IS_LATE, IS_EARLY_LEAVE)
VALUES (SEQ_OA_ATTENDANCE.NEXTVAL, 1, TO_DATE('2026-01-03', 'YYYY-MM-DD'), 
        TO_TIMESTAMP('2026-01-03 09:20:00', 'YYYY-MM-DD HH24:MI:SS'),
        TO_TIMESTAMP('2026-01-03 18:05:00', 'YYYY-MM-DD HH24:MI:SS'),
        '北京市海淀区', '北京市海淀区', 'LATE', 8.75, 1, 0);

-- 插入测试请假申请
INSERT INTO OA_LEAVE_REQUEST (REQUEST_ID, USER_ID, LEAVE_TYPE, START_TIME, END_TIME, DAYS, REASON, STATUS)
VALUES (SEQ_OA_LEAVE_REQUEST.NEXTVAL, 1, 'SICK', 
        TO_TIMESTAMP('2026-01-08 09:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        TO_TIMESTAMP('2026-01-08 18:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        1, '感冒发烧，需要休息', 'PENDING');

-- 插入测试加班申请
INSERT INTO OA_OVERTIME_REQUEST (REQUEST_ID, USER_ID, OVERTIME_DATE, START_TIME, END_TIME, HOURS, REASON, STATUS)
VALUES (SEQ_OA_OVERTIME_REQUEST.NEXTVAL, 1, TO_DATE('2026-01-05', 'YYYY-MM-DD'),
        TO_TIMESTAMP('2026-01-05 18:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        TO_TIMESTAMP('2026-01-05 21:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        3, '项目紧急上线', 'APPROVED');

-- 插入测试出差申请
INSERT INTO OA_BUSINESS_TRIP (TRIP_ID, USER_ID, DESTINATION, START_TIME, END_TIME, DAYS, PURPOSE, TRANSPORT_TYPE, ESTIMATED_COST, STATUS)
VALUES (SEQ_OA_BUSINESS_TRIP.NEXTVAL, 1, '上海市', 
        TO_TIMESTAMP('2026-01-15 08:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        TO_TIMESTAMP('2026-01-17 20:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        3, '客户拜访及项目洽谈', 'TRAIN', 2500, 'PENDING');

-- 插入测试月度汇总
INSERT INTO OA_ATTENDANCE_SUMMARY (SUMMARY_ID, USER_ID, YEAR_MONTH, WORK_DAYS, ACTUAL_DAYS, LATE_TIMES, EARLY_LEAVE_TIMES, ABSENT_DAYS, LEAVE_DAYS, OVERTIME_HOURS, TRIP_DAYS, ATTENDANCE_RATE)
VALUES (SEQ_OA_ATTENDANCE_SUMMARY.NEXTVAL, 1, '2026-01', 22, 20, 2, 0, 0, 1, 8.5, 3, 95.45);

COMMIT;
