-- ========================================
-- OA Attendance Management System Schema (MySQL)
-- ========================================

SET NAMES utf8mb4;

-- 1. Attendance Record Table
CREATE TABLE IF NOT EXISTS OA_ATTENDANCE (
    ATTENDANCE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(32) NOT NULL,
    WORK_DATE DATE NOT NULL,
    CLOCK_IN_TIME DATETIME,
    CLOCK_OUT_TIME DATETIME,
    CLOCK_IN_LOCATION VARCHAR(200),
    CLOCK_OUT_LOCATION VARCHAR(200),
    STATUS VARCHAR(20) DEFAULT 'NORMAL',
    WORK_HOURS DECIMAL(5,2),
    IS_LATE TINYINT(1) DEFAULT 0,
    IS_EARLY_LEAVE TINYINT(1) DEFAULT 0,
    REMARK VARCHAR(500),
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX IDX_ATTENDANCE_USER_DATE (USER_ID, WORK_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2. Leave Request Table
CREATE TABLE IF NOT EXISTS OA_LEAVE_REQUEST (
    REQUEST_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(32) NOT NULL,
    LEAVE_TYPE VARCHAR(50) NOT NULL,
    START_TIME DATETIME NOT NULL,
    END_TIME DATETIME NOT NULL,
    DAYS DECIMAL(5,1) NOT NULL,
    REASON TEXT,
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    APPROVER_ID VARCHAR(32),
    APPROVE_TIME DATETIME,
    APPROVE_REMARK VARCHAR(500),
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX IDX_LEAVE_USER (USER_ID),
    INDEX IDX_LEAVE_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3. Overtime Request Table
CREATE TABLE IF NOT EXISTS OA_OVERTIME_REQUEST (
    REQUEST_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(32) NOT NULL,
    OVERTIME_DATE DATE NOT NULL,
    START_TIME DATETIME NOT NULL,
    END_TIME DATETIME NOT NULL,
    HOURS DECIMAL(5,2) NOT NULL,
    REASON TEXT,
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    APPROVER_ID VARCHAR(32),
    APPROVE_TIME DATETIME,
    APPROVE_REMARK VARCHAR(500),
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX IDX_OVERTIME_USER (USER_ID),
    INDEX IDX_OVERTIME_DATE (OVERTIME_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 4. Business Trip Table
CREATE TABLE IF NOT EXISTS OA_BUSINESS_TRIP (
    TRIP_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(32) NOT NULL,
    DESTINATION VARCHAR(200) NOT NULL,
    START_TIME DATETIME NOT NULL,
    END_TIME DATETIME NOT NULL,
    DAYS DECIMAL(5,1) NOT NULL,
    PURPOSE TEXT,
    TRANSPORT_TYPE VARCHAR(50),
    ESTIMATED_COST DECIMAL(10,2),
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    APPROVER_ID VARCHAR(32),
    APPROVE_TIME DATETIME,
    APPROVE_REMARK VARCHAR(500),
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX IDX_TRIP_USER (USER_ID),
    INDEX IDX_TRIP_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 5. Attendance Rule Table
CREATE TABLE IF NOT EXISTS OA_ATTENDANCE_RULE (
    RULE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    RULE_NAME VARCHAR(100) NOT NULL,
    WORK_START_TIME VARCHAR(10) DEFAULT '09:00',
    WORK_END_TIME VARCHAR(10) DEFAULT '18:00',
    LATE_THRESHOLD_MINUTES INT DEFAULT 15,
    EARLY_LEAVE_THRESHOLD_MINUTES INT DEFAULT 15,
    WORK_DAYS_PER_WEEK INT DEFAULT 5,
    IS_FLEXIBLE TINYINT(1) DEFAULT 0,
    IS_DEFAULT TINYINT(1) DEFAULT 0,
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 6. Attendance Summary Table
CREATE TABLE IF NOT EXISTS OA_ATTENDANCE_SUMMARY (
    SUMMARY_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(32) NOT NULL,
    YEAR_MONTH VARCHAR(7) NOT NULL,
    WORK_DAYS INT DEFAULT 0,
    ACTUAL_DAYS INT DEFAULT 0,
    LATE_TIMES INT DEFAULT 0,
    EARLY_LEAVE_TIMES INT DEFAULT 0,
    ABSENT_DAYS INT DEFAULT 0,
    LEAVE_DAYS DECIMAL(5,1) DEFAULT 0,
    OVERTIME_HOURS DECIMAL(6,2) DEFAULT 0,
    TRIP_DAYS DECIMAL(5,1) DEFAULT 0,
    ATTENDANCE_RATE DECIMAL(5,2),
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY UK_SUMMARY_USER_MONTH (USER_ID, YEAR_MONTH)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Initialize Default Data
INSERT INTO OA_ATTENDANCE_RULE (RULE_NAME, WORK_START_TIME, WORK_END_TIME, LATE_THRESHOLD_MINUTES, EARLY_LEAVE_THRESHOLD_MINUTES, WORK_DAYS_PER_WEEK, IS_FLEXIBLE, IS_DEFAULT)
VALUES ('Standard Working Hours', '09:00', '18:00', 15, 15, 5, 0, 1);

INSERT INTO OA_ATTENDANCE_RULE (RULE_NAME, WORK_START_TIME, WORK_END_TIME, LATE_THRESHOLD_MINUTES, EARLY_LEAVE_THRESHOLD_MINUTES, WORK_DAYS_PER_WEEK, IS_FLEXIBLE, IS_DEFAULT)
VALUES ('Flexible Working Hours', '09:00', '18:00', 30, 30, 5, 1, 0);

COMMIT;
