-- =====================================================
-- OA系统 Oracle 数据库脚本
-- 注意: 这是从MySQL转换而来,需要根据实际情况调整
-- =====================================================

-- 1. 员工表
CREATE TABLE SYS_EMPLOYEE (
    EMP_ID VARCHAR2(32) PRIMARY KEY,
    EMP_NAME VARCHAR2(50) NOT NULL,
    PASSWORD VARCHAR2(100),
    SEX VARCHAR2(10),
    BIRTHDAY DATE,
    TEL VARCHAR2(20),
    EMAIL VARCHAR2(50),
    DEP_ID VARCHAR2(32),
    POS_ID VARCHAR2(32),
    CREATE_TIME DATE DEFAULT SYSDATE
);

-- 2. 部门表
CREATE TABLE SYS_DEPARTMENT (
    DEP_ID VARCHAR2(32) PRIMARY KEY,
    DEP_NAME VARCHAR2(50) NOT NULL,
    PARENT_ID VARCHAR2(32),
    CREATE_TIME DATE DEFAULT SYSDATE
);

-- 3. 职位表
CREATE TABLE SYS_POSITION (
    POS_ID VARCHAR2(32) PRIMARY KEY,
    POS_NAME VARCHAR2(50) NOT NULL,
    CREATE_TIME DATE DEFAULT SYSDATE
);

-- 4. 会议室表
CREATE TABLE OA_MEETING_ROOM (
    ROOM_ID VARCHAR2(32) PRIMARY KEY,
    ROOM_NAME VARCHAR2(100) NOT NULL,
    LOCATION VARCHAR2(100),
    CAPACITY NUMBER(10),
    FACILITIES VARCHAR2(500),
    STATE NUMBER(1) DEFAULT 0
);

-- 5. 会议预定表
CREATE TABLE OA_MEETING_BOOK (
    BOOK_ID VARCHAR2(32) PRIMARY KEY,
    ROOM_ID VARCHAR2(32),
    BOOKER_ID VARCHAR2(32),
    MEETING_THEME VARCHAR2(200),
    START_TIME DATE,
    END_TIME DATE,
    STATUS NUMBER(1) DEFAULT 0,
    CREATE_TIME DATE DEFAULT SYSDATE
);

-- 6. 物资表
CREATE TABLE OA_MATERIAL (
    MAT_ID VARCHAR2(32) PRIMARY KEY,
    MAT_NAME VARCHAR2(100) NOT NULL,
    MAT_TYPE VARCHAR2(50),
    SPECIFICATION VARCHAR2(100),
    UNIT_PRICE NUMBER(10,2),
    STOCK_COUNT NUMBER(10) DEFAULT 0,
    USED_COUNT NUMBER(10) DEFAULT 0
);

-- 7. 物资申请表
CREATE TABLE OA_MAT_APPLY (
    APPLY_ID VARCHAR2(32) PRIMARY KEY,
    MAT_ID VARCHAR2(32),
    APPLICANT_ID VARCHAR2(32),
    APPLY_COUNT NUMBER(10),
    REASON VARCHAR2(500),
    STATUS NUMBER(1) DEFAULT 0,
    CREATE_TIME DATE DEFAULT SYSDATE
);

-- 8. 文档表
CREATE TABLE OA_DOCUMENT (
    DOC_ID VARCHAR2(32) PRIMARY KEY,
    DOC_NAME VARCHAR2(200) NOT NULL,
    DOC_TYPE VARCHAR2(20),
    PARENT_ID VARCHAR2(32) DEFAULT '0',
    FILE_PATH VARCHAR2(500),
    FILE_SIZE NUMBER(20),
    UPLOADER_ID VARCHAR2(32),
    CREATE_TIME DATE DEFAULT SYSDATE
);

-- 9. 工作流表
CREATE TABLE OA_WORKFLOW (
    FLOW_ID VARCHAR2(32) PRIMARY KEY,
    FLOW_TYPE VARCHAR2(50),
    TITLE VARCHAR2(200),
    INITIATOR_ID VARCHAR2(32),
    CURRENT_APPROVER_ID VARCHAR2(32),
    STATUS NUMBER(1) DEFAULT 0,
    PRIORITY VARCHAR2(20),
    FLOW_DATA CLOB,
    CREATE_TIME DATE DEFAULT SYSDATE,
    UPDATE_TIME DATE DEFAULT SYSDATE
);

-- 10. 工作流日志表
CREATE TABLE OA_WORKFLOW_LOG (
    LOG_ID VARCHAR2(32) PRIMARY KEY,
    FLOW_ID VARCHAR2(32),
    APPROVER_ID VARCHAR2(32),
    ACTION VARCHAR2(20),
    COMMENT VARCHAR2(500),
    ACTION_TIME DATE DEFAULT SYSDATE
);

-- 11. 通知表
CREATE TABLE OA_NOTIFICATION (
    NOTIF_ID VARCHAR2(32) PRIMARY KEY,
    USER_ID VARCHAR2(32) NOT NULL,
    TYPE VARCHAR2(20),
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT CLOB,
    IS_READ NUMBER(1) DEFAULT 0,
    CREATE_TIME DATE DEFAULT SYSDATE
);

-- 12. 操作日志表
CREATE TABLE OA_ACTIVITY_LOG (
    LOG_ID VARCHAR2(32) PRIMARY KEY,
    USER_ID VARCHAR2(32) NOT NULL,
    ACTION VARCHAR2(100),
    DETAIL CLOB,
    IP_ADDRESS VARCHAR2(50),
    CREATE_TIME DATE DEFAULT SYSDATE
);

-- 13. 角色表
CREATE TABLE OA_ROLE (
    ROLE_ID VARCHAR2(32) PRIMARY KEY,
    ROLE_NAME VARCHAR2(50) NOT NULL,
    ROLE_DESC VARCHAR2(200),
    PERMISSIONS CLOB,
    CREATE_TIME DATE DEFAULT SYSDATE
);

-- 14. 用户角色关联表
CREATE TABLE OA_USER_ROLE (
    USER_ID VARCHAR2(32),
    ROLE_ID VARCHAR2(32),
    PRIMARY KEY (USER_ID, ROLE_ID)
);

-- 15. 车辆表
CREATE TABLE OA_CAR (
    CAR_ID VARCHAR2(32) PRIMARY KEY,
    CAR_LICENCE VARCHAR2(20) NOT NULL,
    CAR_TYPE VARCHAR2(50),
    BRAND VARCHAR2(50),
    SEATS NUMBER(10),
    STATE NUMBER(1) DEFAULT 0,
    REMARK VARCHAR2(200),
    CREATE_TIME DATE DEFAULT SYSDATE
);

-- 创建序列 (用于自动生成ID,如果需要)
CREATE SEQUENCE SEQ_OA_ID START WITH 1000 INCREMENT BY 1;

-- 初始化数据
INSERT INTO SYS_DEPARTMENT VALUES ('D001', '技术部', '0', SYSDATE);
INSERT INTO SYS_DEPARTMENT VALUES ('D002', '市场部', '0', SYSDATE);

INSERT INTO SYS_POSITION VALUES ('P001', '经理', SYSDATE);
INSERT INTO SYS_POSITION VALUES ('P002', '员工', SYSDATE);

INSERT INTO SYS_EMPLOYEE VALUES (
    'E001', 'Admin', 'e10adc3949ba59abbe56e057f20f883e', 
    '男', TO_DATE('1990-01-01', 'YYYY-MM-DD'), 
    '13800138000', 'admin@oa.com', 'D001', 'P001', SYSDATE
);

INSERT INTO OA_CAR VALUES ('C001', '京A88888', '轿车', '奥迪A6', 5, 0, NULL, SYSDATE);
INSERT INTO OA_CAR VALUES ('C002', '京A66666', '商务车', '别克GL8', 7, 1, NULL, SYSDATE);

COMMIT;
